server:
  port: 8081

socket:
  setSoTimeout(100*1000):

spring:
  servlet:
    multipart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/conciliaciones?useSSL=false
    username: root
    password:


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
